### ISSUE TITLE
EventGhost receiving incorrect information from SmartApp

### ISSUE THREAD

**Issue by dseg42** [aderusha/SmartThings#2]
Hello -
Github removed private messaging so I am hoping you read this here.
I've been really stuck on a problem I am having with trying to get EG to receive the correct events from SmartThings.
I currently have a thread located here:
https://community.smartthings.com/t/send-events-to-eventghost/22473/67
Basically EG will receive events from SmartThings but most of the time EG will read the the incorrect binary value (open/close) or miss the event completely.  I found this to be extremely useful but I am still having this issue.  Please let me know if you would be willing to help with a debug/trouble shooting.
I did also find other people with the same problem.

**Comment by aderusha** [comment]
I am no longer using SmartThings or EventGhost in my environment so I don't really have any way to assist in a debug session.
